### ISSUE TITLE
issue when importing reproject

### ISSUE THREAD

**Issue by baobabyoo** [astrofrog/reproject#103]
Hello,

I downloaded the .zip file of reproject,
and made installation using "python ./setup.py install".
It seems to be successful, but when I import reproject, 
I ran into the error message as follows:

> > > import reproject
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "reproject/**init**.py", line 14, in <module>
> > >     from .spherical_intersect import reproject_exact
> > >   File "reproject/spherical_intersect/**init**.py", line 5, in <module>
> > >     from .high_level import *
> > >   File "reproject/spherical_intersect/high_level.py", line 6, in <module>
> > >     from .core import _reproject_celestial
> > >   File "reproject/spherical_intersect/core.py", line 11, in <module>
> > >     from ._overlap import _compute_overlap
> > > ImportError: No module named _overlap

Is there any clue of what is missing? 
Thanks very much.

Best wishes,
Baobab

**Comment by astrofrog** [comment]
@baobabyoo - can you post the full output for ``python setup.py install``?

**Comment by baobabyoo** [comment]
(uvcombine)hlu@pc018656$ python ./setup.py install
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
reproject/spherical_intersect/setup_package.py:1: RuntimeWarning: Parent module 'reproject.spherical_intersect' not found while handling absolute import
  import os
reproject/spherical_intersect/setup_package.py:2: RuntimeWarning: Parent module 'reproject.spherical_intersect' not found while handling absolute import
  from distutils.core import Extension
/media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/lib/python2.7/site-packages/setuptools-22.0.5-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.3.dev' to '0.3.dev0'
running install
running bdist_egg
running egg_info
writing requirements to reproject.egg-info/requires.txt
writing reproject.egg-info/PKG-INFO
writing top-level names to reproject.egg-info/top_level.txt
writing dependency_links to reproject.egg-info/dependency_links.txt
writing entry points to reproject.egg-info/entry_points.txt
reading manifest file 'reproject.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching 'astropy_helpers/README.rst'
warning: no files found matching 'astropy_helpers/CHANGES.rst'
warning: no files found matching 'astropy_helpers/LICENSE.rst'
warning: no files found matching '*' under directory 'astropy_helpers/licenses'
warning: no files found matching 'astropy_helpers/ez_setup.py'
warning: no files found matching 'astropy_helpers/ah_bootstrap.py'
warning: no files found matching '*.py' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.pyx' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.c' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.h' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*' under directory 'astropy_helpers/astropy_helpers.egg-info'
warning: no files found matching '*' under directory 'astropy_helpers/astropy_helpers/sphinx'
no previously-included directories found matching 'astropy_helpers/build'
no previously-included directories found matching 'astropy_helpers/astropy_helpers/tests'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'reproject.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'reproject/spherical_intersect/_overlap.c' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/reproject
copying build/lib.linux-x86_64-2.7/reproject/__init__.py -> build/bdist.linux-x86_64/egg/reproject
copying build/lib.linux-x86_64-2.7/reproject/_compiler.c -> build/bdist.linux-x86_64/egg/reproject
copying build/lib.linux-x86_64-2.7/reproject/cython_version.py -> build/bdist.linux-x86_64/egg/reproject
copying build/lib.linux-x86_64-2.7/reproject/version.py -> build/bdist.linux-x86_64/egg/reproject
creating build/bdist.linux-x86_64/egg/reproject/interpolation
copying build/lib.linux-x86_64-2.7/reproject/interpolation/__init__.py -> build/bdist.linux-x86_64/egg/reproject/interpolation
copying build/lib.linux-x86_64-2.7/reproject/interpolation/high_level.py -> build/bdist.linux-x86_64/egg/reproject/interpolation
copying build/lib.linux-x86_64-2.7/reproject/interpolation/core.py -> build/bdist.linux-x86_64/egg/reproject/interpolation
creating build/bdist.linux-x86_64/egg/reproject/interpolation/tests
copying build/lib.linux-x86_64-2.7/reproject/interpolation/tests/__init__.py -> build/bdist.linux-x86_64/egg/reproject/interpolation/tests
copying build/lib.linux-x86_64-2.7/reproject/interpolation/tests/test_core.py -> build/bdist.linux-x86_64/egg/reproject/interpolation/tests
copying build/lib.linux-x86_64-2.7/reproject/conftest.py -> build/bdist.linux-x86_64/egg/reproject
copying build/lib.linux-x86_64-2.7/reproject/wcs_utils.py -> build/bdist.linux-x86_64/egg/reproject
creating build/bdist.linux-x86_64/egg/reproject/tests
copying build/lib.linux-x86_64-2.7/reproject/tests/__init__.py -> build/bdist.linux-x86_64/egg/reproject/tests
creating build/bdist.linux-x86_64/egg/reproject/tests/data
copying build/lib.linux-x86_64-2.7/reproject/tests/data/gc_eq.hdr -> build/bdist.linux-x86_64/egg/reproject/tests/data
copying build/lib.linux-x86_64-2.7/reproject/tests/data/cube.hdr -> build/bdist.linux-x86_64/egg/reproject/tests/data
copying build/lib.linux-x86_64-2.7/reproject/tests/data/gc_ga.hdr -> build/bdist.linux-x86_64/egg/reproject/tests/data
copying build/lib.linux-x86_64-2.7/reproject/tests/coveragerc -> build/bdist.linux-x86_64/egg/reproject/tests
copying build/lib.linux-x86_64-2.7/reproject/tests/setup_package.py -> build/bdist.linux-x86_64/egg/reproject/tests
copying build/lib.linux-x86_64-2.7/reproject/tests/test_utils.py -> build/bdist.linux-x86_64/egg/reproject/tests
copying build/lib.linux-x86_64-2.7/reproject/tests/test_high_level.py -> build/bdist.linux-x86_64/egg/reproject/tests
copying build/lib.linux-x86_64-2.7/reproject/utils.py -> build/bdist.linux-x86_64/egg/reproject
creating build/bdist.linux-x86_64/egg/reproject/healpix
copying build/lib.linux-x86_64-2.7/reproject/healpix/__init__.py -> build/bdist.linux-x86_64/egg/reproject/healpix
copying build/lib.linux-x86_64-2.7/reproject/healpix/high_level.py -> build/bdist.linux-x86_64/egg/reproject/healpix
copying build/lib.linux-x86_64-2.7/reproject/healpix/core.py -> build/bdist.linux-x86_64/egg/reproject/healpix
creating build/bdist.linux-x86_64/egg/reproject/healpix/tests
copying build/lib.linux-x86_64-2.7/reproject/healpix/tests/__init__.py -> build/bdist.linux-x86_64/egg/reproject/healpix/tests
creating build/bdist.linux-x86_64/egg/reproject/healpix/tests/data
copying build/lib.linux-x86_64-2.7/reproject/healpix/tests/data/bayestar.fits.gz -> build/bdist.linux-x86_64/egg/reproject/healpix/tests/data
copying build/lib.linux-x86_64-2.7/reproject/healpix/tests/data/reference_result.fits -> build/bdist.linux-x86_64/egg/reproject/healpix/tests/data
copying build/lib.linux-x86_64-2.7/reproject/healpix/tests/setup_package.py -> build/bdist.linux-x86_64/egg/reproject/healpix/tests
copying build/lib.linux-x86_64-2.7/reproject/healpix/tests/test_utils.py -> build/bdist.linux-x86_64/egg/reproject/healpix/tests
copying build/lib.linux-x86_64-2.7/reproject/healpix/tests/test_healpix.py -> build/bdist.linux-x86_64/egg/reproject/healpix/tests
copying build/lib.linux-x86_64-2.7/reproject/healpix/utils.py -> build/bdist.linux-x86_64/egg/reproject/healpix
copying build/lib.linux-x86_64-2.7/reproject/_compiler.so -> build/bdist.linux-x86_64/egg/reproject
copying build/lib.linux-x86_64-2.7/reproject/array_utils.py -> build/bdist.linux-x86_64/egg/reproject
creating build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/__init__.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/overlapArea.c -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/high_level.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/_overlap.c -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/mNaN.h -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/core.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/_overlap.so -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
creating build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/tests/__init__.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/tests/test_overlap.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/tests/test_reproject.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/tests/test_high_level.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/reproject_slice_c.h -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/overlap.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/setup_package.py -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/overlapArea.h -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/reproject_slice_c.c -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/spherical_intersect/overlapAreaPP.c -> build/bdist.linux-x86_64/egg/reproject/spherical_intersect
copying build/lib.linux-x86_64-2.7/reproject/_astropy_init.py -> build/bdist.linux-x86_64/egg/reproject
byte-compiling build/bdist.linux-x86_64/egg/reproject/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/cython_version.py to cython_version.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/interpolation/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/interpolation/high_level.py to high_level.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/interpolation/core.py to core.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/interpolation/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/interpolation/tests/test_core.py to test_core.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/conftest.py to conftest.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/wcs_utils.py to wcs_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/tests/setup_package.py to setup_package.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/tests/test_utils.py to test_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/tests/test_high_level.py to test_high_level.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/high_level.py to high_level.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/core.py to core.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/tests/setup_package.py to setup_package.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/tests/test_utils.py to test_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/tests/test_healpix.py to test_healpix.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/healpix/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/array_utils.py to array_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/high_level.py to high_level.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/core.py to core.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests/test_overlap.py to test_overlap.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests/test_reproject.py to test_reproject.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/tests/test_high_level.py to test_high_level.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/overlap.py to overlap.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/setup_package.py to setup_package.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/_astropy_init.py to _astropy_init.pyc
creating stub loader for reproject/_compiler.so
creating stub loader for reproject/spherical_intersect/_overlap.so
byte-compiling build/bdist.linux-x86_64/egg/reproject/_compiler.py to _compiler.pyc
byte-compiling build/bdist.linux-x86_64/egg/reproject/spherical_intersect/_overlap.py to _overlap.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying reproject.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/reproject-0.3.dev0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing reproject-0.3.dev0-py2.7-linux-x86_64.egg
creating /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/lib/python2.7/site-packages/reproject-0.3.dev0-py2.7-linux-x86_64.egg
Extracting reproject-0.3.dev0-py2.7-linux-x86_64.egg to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/lib/python2.7/site-packages
Adding reproject 0.3.dev0 to easy-install.pth file

Installed /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/lib/python2.7/site-packages/reproject-0.3.dev0-py2.7-linux-x86_64.egg
Processing dependencies for reproject==0.3.dev0
Searching for astropy==1.1.2
Best match: astropy 1.1.2
Adding astropy 1.1.2 to easy-install.pth file
Installing fitsinfo script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing fitsheader script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing fits2bitmap script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing fitsdiff script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing fitscheck script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing volint script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing wcslint script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin
Installing samp_hub script to /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/bin

Using /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/lib/python2.7/site-packages
Searching for numpy==1.11.0
Best match: numpy 1.11.0
Adding numpy 1.11.0 to easy-install.pth file

Using /media/DATA/astro_softwares/python/anaconda2/envs/uvcombine/lib/python2.7/site-packages
Finished processing dependencies for reproject==0.3.dev0

**Comment by baobabyoo** [comment]
This seems to be an issue related to the name of files and programs,
or could be missing one file.
Once I change overlap.py to _overlap.py, and comment out the line
"from ._overlap import _compute_overlap" in this file, and also change 
"__all__ = ['compute_overlap']"  to
"__all__ = ['_compute_overlap']"
,then I am able to install with python ./setup.py install,
and "import reproject" doesn't show error messages.

I will see if then I can use this package without a problem.

**Comment by baobabyoo** [comment]
It seems to be working. But I just realized that the package I am using which calls reproject has been edited a lot. So I am lose track of the behavior of the package itself. At least in this way "reproject" doesn't give error message at execution level.

**Comment by astrofrog** [comment]
I'm going to close this as I don't think this is an issue that needs fixing in reproject
