### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by olebole** [astrofrog/reproject#107]
Sorry to bother you again...

The license file which is in the git repository does not get packaged into the pypi tarball.

**Comment by astrofrog** [comment]
@olebole - oops, sorry about that. Will fix!

**Comment by astrofrog** [comment]
@olebole - can you confirm that v0.3.1 is fixed?

**Comment by olebole** [comment]
Confirmed.

**Comment by olebole** [comment]
Ohh -- and thanks for the quick reaction. I just uploaded it and hope it will get accepted by the ftp-masters.
