### ISSUE TITLE
Citable record?

### ISSUE THREAD

**Issue by adrn** [astrofrog/reproject#141]
We're planning to reference and cite all Astropy affiliated packages in the upcoming Astropy v2.0 paper. I couldn't find a citable record for this package - are you interested in creating one so that we can cite it? For example, you can create a [zenodo](zenodo.org) record and just comment back here to let me know that it's done. Please also let me know if you'd like to opt out of a citation and we'll just link to the package. Thanks!

**Comment by astrofrog** [comment]
I'll make a zenodo record

**Comment by astrofrog** [comment]
@adrn - see https://zenodo.org/record/1162674
