### ISSUE TITLE
Cython source reproject/spherical_intersect/_overlap.pyx missing on Pypi

### ISSUE THREAD

**Issue by olebole** [astrofrog/reproject#158]
`reproject/spherical_intersect/_overlap.pyx` is missing in the Pypi package, which makes it impossible to recreate `_overlap.c` with Cython. 

Recreation may be necessary to ensure f.e. Python 3.7 compatibility; see also cython/cython#1955

**Comment by astrofrog** [comment]
@olebole - ah, good to know. I'll try and fix this soon.

**Comment by cdeil** [comment]
reproject and astropy-healpix don't work on Python 3.7 yet; the usual Cython error:
https://gist.github.com/cdeil/915de446954be43fdc8d8b0ec50bc51c

@astrofrog - Do you have time to put out a new release in the near future?

**Comment by astrofrog** [comment]
@cdeil - I've released astropy-healpix v0.2.1 which has re-generated Cython files on Python 3.7. With this, ``pip install reproject`` now works without the need to include the Cython files or update the Cython files here, so I'm going to close this (in general we deliberately avoid including the Cython files).
