### ISSUE TITLE
conda-forge package for Python 3.7

### ISSUE THREAD

**Issue by cdeil** [astrofrog/reproject#165]
Today I tried again switching my Gammapy dev environment from Python 3.6 to 3.7.

It's failing like this:
```
$ conda create -n test123 python=3.7 reproject
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - reproject -> numpy=1.12 -> python[version='>=2.7,<2.8.0a0'] -> openssl=1.0.1
  - reproject -> numpy=1.12 -> python[version='>=2.7,<2.8.0a0'] -> readline=6.2
  - reproject -> numpy=1.12 -> python[version='>=2.7,<2.8.0a0'] -> tk=8.5
Use "conda info <package>" to see the dependencies for each package.
```

I know that pip install would work on Python 3.7 now, see #158 .

But @astrofrog - would it be possible to trigger a re-build somehow on conda-forge to get a conda package for Python 3.7 for reproject?

**Comment by bsipocz** [comment]
I suppose something when wrong when overriding https://github.com/conda-forge/reproject-feedstock/pull/9?

**Comment by astrofrog** [comment]
I'll try and get the Python 3.7 packages to build here: https://github.com/conda-forge/reproject-feedstock/pull/11

**Comment by cdeil** [comment]
@astrofrog - Thanks!
Closing this issue.

For regions we still don't have it. Not sure what needs to be done here or in a new PR to get Python 3.7 for that as well. See https://github.com/conda-forge/regions-feedstock/pull/7#issuecomment-436963591
