### ISSUE TITLE
Support 32-bit float?

### ISSUE THREAD

**Issue by cdeil** [astrofrog/reproject#23]
Do we want to support 32-bit floats as input / output?

Could be useful to avoid making 64-bit copies where very large 32-bit input images are used.

How would this be implemented?
Worth the effort?

**Comment by cdeil** [comment]
As far as I know there's quite some extra effort / boilerplate code to support both 64-bit and 32-bit for this:
http://kbarbary.github.io/blog/cython-and-multiple-numpy-dtypes/

So @astrofrog  – I'd be +1 to close this issue now and only re-consider this if more users ask for 32-bit support.

**Comment by astrofrog** [comment]
For now I wonder if it would be worth adding a statement to ``parse_input_data`` (after #67 is merged) to use ``asarray(..., dtype=float)`` to re-cast data if it's not already 64-bit.

**Comment by cdeil** [comment]
So currently an error is raised if the user inputs 32-bit float data?
If so, then yes, I think silently casting to 64-bit float and mentioning it in the docs somewhere would be best.

**Comment by astrofrog** [comment]
Implemented full support in https://github.com/astrofrog/reproject/pull/73. I don't think it needs documenting, because I think this does what users expect - it always works, and returns normal float values.
