### ISSUE TITLE
Make reprojection work for mosaicing with multi extension fits

### ISSUE THREAD

**Issue by bsipocz** [astrofrog/reproject#58]
``reprojection`` should accept multiple hdus and then figure out the least common multiple image and reproject all the hdus into that, either individually or to a single final mosaic.

Basically do what ``montage.mosaic`` does.

**Comment by astrofrog** [comment]
Just a summary of the discussion we had following this at the pyastro15 workshop: reproject itself should stay as-is but we'll want a function that can take multiple HDUs and then figure out the output WCS to use, and later we can then create an easy 'mosaic' function that just wraps the function to find the header, and then calls reproject on all tiles before combining them.

@bsipocz - just to check, do you still plan to try and work on the first issue, namely making a function that can figure out the output WCS to use?

**Comment by bsipocz** [comment]
@astrifrig - yes, it'll be a good task to finish on my way back home
tomorrow. Also I'll fix the doc test running.

**Comment by bsipocz** [comment]
Sorry, was the autocorrect...

**Comment by astrofrog** [comment]
@bsipocz - sounds good - enjoy the rest of the weekend! :)

**Comment by astrofrog** [comment]
Closing this and opened https://github.com/astrofrog/reproject/issues/74
