### ISSUE TITLE
Remaining issues regarding HEALPIX projection

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/reproject#64]
A few remaining things to do for the HEALPIX projection:

* [x] @lpsinger - do we need to use ``sky_to_sky`` and the healpy rotator class, or can we switch to using a slightly modified version of the function here: https://github.com/astrofrog/reproject/blob/master/reproject/wcs_utils.py#L17 which uses astropy.coordinates?

* [x] Why does the reference header define ``COORDSYS`` in the examples? As far as I know this is not part of the FITS standard, and instead we should use ``RADESYS`` if the header is in RA/Dec and otherwise the coordinate system is clear from the ``CTYPE1``/``CTYPE2``. For normal (non-healpix) WCS we can use the existing Astropy function ``wcs_to_celestial_frame`` to return a coordinate frame from the WCS (and it will figure out all the equinox etc. stuff correctly)

* [x] I think we want to avoid dealing with filenames in ``healpix.py`` and instead have any I/O in the high-level ``reproject`` function to keep things simple.

* [x] We need to improve the test coverage, which took a dive down with these changes

* [x] We need to document the HEALPIX reprojection in the main docs.

* [x] The healpix code should be moved to a sub-directory called ``healpix`` to keep things tidy

**Comment by astrofrog** [comment]
I'm going to try and open a pull request to address the first two, and maybe @lpsinger you could test it out?

**Comment by astrofrog** [comment]
Hmm I guess the issue is that we don't support ecliptic coordinate conversion yet so for that we have to still use the existing rotator class.

**Comment by astrofrog** [comment]
Just for info, a WIP for the coordinate conversion using Astropy is here: https://github.com/astrofrog/reproject/pull/65

**Comment by cdeil** [comment]
@astrofrog  – You've done most (all?) of these things in #67, no?

**Comment by astrofrog** [comment]
Yes, will close when #67 is merged
