### ISSUE TITLE
RTD build failing

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/reproject#71]
Fun times ahead:

* Matplotlib is <1.4 on RTD but need >= 1.4 for plot directive to work properly (and pip won't update matplotlib on RTD)
* Healpy complains about setuptools not being recent enough: ``The required version of setuptools (>=14.3.1) is not available``

Can't update setuptools ourselves because pip needs to run ``egg_info`` on all dependencies before installing anything.

I think I'm just going to switch to static plots in the docs. I don't have time to waste trying to find workarounds for the above.

**Comment by astrofrog** [comment]
If I use static plots it will also help with the sporadic Travis failures.

**Comment by cdeil** [comment]
I've had a similar problem for scipy on readthedocs.

As far as I understand this is a known issue with no solution in sight, see https://github.com/rtfd/readthedocs.org/issues/857#issuecomment-99520696 or https://github.com/rtfd/readthedocs.org/issues/896#issuecomment-52899973

**Comment by shoyer** [comment]
@astrofrog just a note -- I've been able to get `matplotlib==1.4.0` to install on read the docs via `requirements.txt`. `matplotlib==1.4.2` didn't work (no idea why that makes a difference).

**Comment by astrofrog** [comment]
@shoyer - ah ok, thanks!
