### ISSUE TITLE
Test on AppVeyor

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/reproject#81]
We should enable continuous integration on AppVeyor. If anyone wants to open a PR for this, I can flick the switch on the AppVeyor side! (we should just be able to re-use the yaml file from other astropy projects)

**Comment by cdeil** [comment]
There was an issue on the Windows build with MSVC that @mwcraig patched here:
https://github.com/astropy/conda-builder-affiliated/pull/31

**Comment by astrofrog** [comment]
@cdeil @mwcraig - thanks! I don't have time in the next couple of weeks to merge that change in or set up AppVeyor, so if anyone else would like to give it a go, please feel free to!
