### ISSUE TITLE
Re-release under GPL

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/reproject#82]
I feel dirty writing this, but I have to re-release under GPL. Healpy is GPL v2 because of HEALPIX being GPL v2, and importing is enough to make reproject GPL. This is really annoying because I was hoping to use reproject in APLpy but now I can't. There are two ways forward:

* Ask the HEALPIX developers to re-release under LGPL, which I think solves this issue

* Write out own implementation of HEALPIX which may not be so hard because we actually only use a very small fraction of the functionality in HEALPIX

**UPDATE**: as discussed below, not relicensing under GPL since it's just for an optional dependency, so have just added a note that if functions using that dependency are used, it should be treated as GPL.

**Comment by astrofrog** [comment]
Also, since it would be illegal to have a BSD release out there, I'm re-releasing 0.1 rather than releasing 0.1.1

**Comment by cdeil** [comment]
I've had this issue for Gammapy ... Sherpa is GPL at the moment (although that might change).

After discussions with several people I'm not pretty sure that an optional GPL dependency (like healpy is for reproject) is OK for a BSD package (see [here](https://gammapy.readthedocs.org/en/latest/install.html#bsd-or-gpl-license)).

Note that @taldcroft sees it the same way and e.g. also released https://github.com/taldcroft/datastack under BSD-3.

So maybe at least don't rush the license change to GPL for reproject / aplpy ... try to see if the current situation is OK or ask the HEALPIX / healpy guys to consider LGPL ...

**Comment by astrofrog** [comment]
@cdeil - yes, I think the fact it's an optional dependency makes it a grey area. I won't change the license today. Do you know any of the HEALPIX developers? (since they are the ones who would need to change to LGPL)

**Comment by cdeil** [comment]
@astrofrog – No, I don't know anyone from HEALPIX. But re-licensing is probably impossible for a 18 year old package with many contributors from many institutes: http://healpix.sourceforge.net/credits.php

**Comment by astrofrog** [comment]
I've been thinking about this a bit more, and WCSLIB supports the HPX projection, which may do a lot of the hard work, and it might be possible for us to write a completely independent healpix interpolation function based on that. We are only using a very small fraction of the actual HEALPIX code.

**Comment by astrofrog** [comment]
As a stop-gap measure, I've added notes that any package using the healpix-related functions needs to abide by the GPL: https://github.com/astrofrog/reproject/commit/8ec31a51d31f83414064209f95fb5e06b556d8d5 - not perfect, but better than nothing...

But now I'm seriously considering developing our own algorithm, leveraging WCSLIB

**Comment by astrofrog** [comment]
Ohhhhhhhh, from WCSLIB site:

```
Utility program HPXcvt is included with WCSLIB. It converts 1D HEALPix pixelization data stored in a variety of forms in FITS, including ring or nested organization in a binary table extension, into a 2D primary image array with HPX or XPH coordinate representation.
```

**Comment by astrofrog** [comment]
:tada:

**Comment by astrofrog** [comment]
I've emailed Mark to see if he can re-arrange the WCSLIB code to expose that functionality in the library (rather than as a command-line utility). But that certainly seems like a promising way forward.

**Comment by ngoldbaum** [comment]
Sorry for stirring up trouble! We had to deal with exactly this issue (the original Healpix libraries being licensed under the GPL) back when we relicensed yt from GPL to BSD.

**Comment by astrofrog** [comment]
@ngoldbaum - how did you deal with it? Did you implement your own algorithm instead?

**Comment by astrofrog** [comment]
@ngoldbaum - also, I'm very grateful you brought this up!

**Comment by ngoldbaum** [comment]
We ended up stubbing out the code that used to use GPL code:

https://bitbucket.org/yt_analysis/yt/commits/63abce2007b74362a27c57283244a425325162df

It was less of a pain for us because we were only using it in one place - HEALPIX projections for volume rendering ray tracing - that was not key functionality.

That said, I'm curious how WCSLIB is able to link against the healpix library but not be GPL itself. As far as I'm aware, it's not kosher to link against a GPL library in an LGPL library. Are they using a cleanroom reimplementation of the healpix algorithm?

**Comment by astrofrog** [comment]
@ngoldbaum - WCSLIB doesn't link against HEALPIX, it has its own implementation as far as I can tell. What it does is a bit different too - it simply allows one to reproject to the HPX projection in a lossless way - see http://www.atnf.csiro.au/people/mcalabre/WCS/mhg_20070725.pdf for more details. In reproject we could use that to reproject HEALPIX to HPX then use WCSLIB to then convert to other projections.

**Comment by cdeil** [comment]
There have been several discussions about BSD Python packages that import a GPL package as an optional dependency. I think there's mostly agreement that this is OK? Is it useful to keep this issue in the code tracker open?

**Comment by astrofrog** [comment]
@cdeil - I'd still like to switch to using WCSLIB in future if possible, but indeed I can close this because I will not re-release under GPL.

**Comment by astrofrog** [comment]
(see https://github.com/astrofrog/reproject/issues/83 about WCSLIB)
