### ISSUE TITLE
Switch to using WCSLIB for HEALPIX

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/reproject#83]
WCSLIB includes a utility to go from a HEALPIX representation to a 2d HPX projection in an exact way with no interpolation (from which we can then use the existing celestial reprojection tools in reproject). Switching to using WCSLIB would therefore have the following advantages:
- It is LGPL instead of GPL so https://github.com/astrofrog/reproject/issues/82 is no longer an issue since we could drop the HEALPIX dependency.
- It is bundled in Astropy so we could maybe call the WCSLIB functions from there instead of having it as an extra dependency (maybe @mdboom could say if this is possible?)
- Since transforming to HPX is lossless, we can then use reproject_exact on the result and therefore implement #80 (cc @cdeil)

The downsides are:
- Not clear if there is a conversion tool for HPX -> HEALPIX but in principle there's no reason we couldn't try and contribute that to WCSLIB
- At the moment, this is a command-line utility in WCSLIB so we'd need that functionality to be moved to the library. I've asked Mark if this would be possible.

This is not something we can do immediately because of the two downsides, but I think we could make it work in the mid-term future!

**Comment by cdeil** [comment]
Thanks Tom, I fully agree that if we can get the functionality we need from WCSLib or by implementing some things ourselves, without the HEALPIX dependency, it's worth some effort.

Side comment – Even after reading about HEALPIX a bit (e.g. at https://en.wikipedia.org/wiki/HEALPix, or the HEALPIX and WCSLib pages), I'm still confused. If someone has the time to write a more hands-on / software-oriented tutorial introduction to HEALPIX, i.e. what is in WCSLib / astropy.wcs and what is in HEALPIX / healpy and give simple examples of HEALPIX FITS files ... I would find this hugely helpful and I suspect other astronomers that only need to work with HEALPIX rarely and want to grok it and know how to work with it in ~ 1 hour would do too.

**Comment by astrofrog** [comment]
> At the moment, this is a command-line utility in WCSLIB so we'd need that functionality to be moved to the library. I've asked Mark if this would be possible.

I got a positive reply from Mark, and he will look into it!

@cdeil - I agree, it would be nice to have a simpler description of the HEALPIX algorithm (I don't understand all the details myself)

**Comment by astrofrog** [comment]
No longer an issue anymore now that we use astropy-healpix (https://github.com/astrofrog/reproject/pull/139)
