### ISSUE TITLE
plate carrée projection in DS9 and ALADIN: coordinate grid.

### ISSUE THREAD

**Issue by ggreco77** [astrofrog/reproject#85]
Hi folk,
 when I try to project an Healpix image in plate carrée projection,
the  coordinate grid in DS9 are shifted - as in attachment image. 
The same in Aladin Sky Atlas but to a limited extent.
This for different input values in the header;
I am attaching an example code:

from astropy.io import fits
hdu_ligo = fits.open(filename_ligo)[1]

target_header = fits.Header.fromstring("""
NAXIS   =                    2
NAXIS1  =                 1000
NAXIS2  =                  800
CTYPE1  = 'RA---CAR'
CRPIX1  =                  500
CRVAL1  =                0
CDELT1  =                 -0.4
CUNIT1  = 'deg     '
CTYPE2  = 'DEC--CAR'
CRPIX2  =                  400
CRVAL2  =                  0.0
CDELT2  =                  0.4
CUNIT2  = 'deg     '
COORDSYS= 'icrs    '
""", sep='\n')

array, footprint = reproject_from_healpix(filename_ligo, target_header)

from astropy.wcs import WCS
target_wcs = WCS(
![ds9_coorgrid_car](https://cloud.githubusercontent.com/assets/11920251/8019158/39fb36ac-0c40-11e5-8592-ed850c507f77.png)
target_header)
array, footprint = reproject_from_healpix(filename_ligo, target_wcs,
                                          shape_out=(240,480))

data = hdu_ligo.data['PROB']
array, footprint = reproject_from_healpix((data, 'icrs'),
                                           target_header, nested=True)

from astropy.coordinates import FK5
array, footprint = reproject_from_healpix((data, FK5(equinox='J2010')),
                                          target_header, nested=True)

fits.writeto('ds9_out.fits', array,target_header)

many thanks,
Giuseppe

**Comment by astrofrog** [comment]
I think this is a ds9 bug, due to the fact that the image covers an area slightly larger than the whole sky (the pixel scale is a bit too big). Try using

```
NAXIS = 2
NAXIS1 = 1000
NAXIS2 = 500
CTYPE1 = 'RA---CAR'
CRPIX1 = 500
CRVAL1 = 0
CDELT1 = -0.36
CUNIT1 = 'deg '
CTYPE2 = 'DEC--CAR'
CRPIX2 = 400
CRVAL2 = 0.0
CDELT2 = 0.36
CUNIT2 = 'deg '
COORDSYS= 'icrs '
```

instead.

**Comment by ggreco77** [comment]
It works as expected.
Many thanks, 
Giuseppe

**Comment by astrofrog** [comment]
@ggreco77 - thanks for confirming!
