### ISSUE TITLE
HEALPIX image reprojection: erroneous display with SAOImage DS9: CRVAL1

### ISSUE THREAD

**Issue by ggreco77** [astrofrog/reproject#90]
The reprojected healpix images are displayed by DS9 with an incorrect right ascension value.
The problem seems to stem from the parameter **CRVAL1 = 180.0** used to set the **_targer_header**_.
By setting **CRVAL1 = 0**, DS9 correctly displays the image.

This problem does not occur using Aladin Sky Atlas.

**Comment by astrofrog** [comment]
@ggreco77 - could this be a ds9 bug? Could you send me the file to thomas.robitaille@gmail.com?

**Comment by astrofrog** [comment]
This appears to be a bug in DS9 unrelated to reproject, so I'll close this.
