### ISSUE TITLE
stable on ReadTheDocs points to 0.2dev248

### ISSUE THREAD

**Issue by mwcraig** [astrofrog/reproject#92]
Not much more to add, see: http://reproject.readthedocs.org/en/stable/

**Comment by astrofrog** [comment]
I think it's going to be to do with the stable tag vs branch again...

cc @eteq @embray

**Comment by astrofrog** [comment]
(ignore previous incorrect reply, didn't check repo)

I think this was because I did a small fix to the docs post-release. Will try and sort this out.

**Comment by astrofrog** [comment]
Fixed :)

**Comment by embray** [comment]
Confused why I got e-mail about this...I wasn't mentioned anywhere in this issue and am not watching this repo ??
