### ISSUE TITLE
Clarify BSD license type

### ISSUE THREAD

**Issue by olebole** [astrofrog/reproject#95]
It is unclear whether the package is licensed under "BSD-2" or "BSD-3": there are many files that claim to be under BSD-3, but then refer to `LICENSE.rst` which is actually BSD-2. This makes it difficult to upload the package to Debian; it was [just rejected](http://lists.alioth.debian.org/pipermail/debian-astro-maintainers/Week-of-Mon-20160201/002456.html) because of the incomplete license I did.

Could I ask to clean this up and to put all files either under BSD-2 or BSD-3?

**Comment by cdeil** [comment]
@astrofrog - I assume it's supposed to be the same license as Astropy, right?
Would a PR from me be helpful or do you want to take care of it?

**Comment by olebole** [comment]
Since this package is now a dependency of another package that is already in Debian (ccdproc): Could this be clarified? Without this, I cannot update the ccdproc package.

**Comment by astrofrog** [comment]
@olebole @cdeil I've updated the license to the 3-clause BSD one (this was an oversight)

**Comment by olebole** [comment]
Could you also adjust the license of `reproject/wcs_utils.py` please? This is still 2-clause BSD.
Also, may I ask to upload a new version to pypi? It is much easier for me to use an official release for the Debian package that to checkout from github.

**Comment by astrofrog** [comment]
Fixed in c3899461d2dce7181a5e1ffe2a2df31060777e31. I'll try to get a release out very soon.

**Comment by olebole** [comment]
Thank you very much, and sorry that I need to be so nitpicky here :-)

**Comment by olebole** [comment]
HI @astrofrog, could I ask you to create a new release here? Reproject is now a dependency of [ccdproc](https://github.com/astropy/ccdproc), so I can't update ccdproc in Debian until reproject is there -- and to get it into Debian, I need a version with the corrected license.

**Comment by astrofrog** [comment]
@olebole - sorry for the delay, reproject v0.3 is now out!
